export { default as bg } from "./bg.svg";
export { default as navLogo } from "./nav-logo.svg";
export { default as bookNow } from "./booknow-bg.svg";
export { default as aboutUs } from "./about-bg.svg";
export { default as whoWeAre } from "./who-we-are.svg";
export { default as iconCommunity } from "./icon-community.svg";
export { default as footerBg } from "./footer-bg.svg";
export { default as bannerDetailImg } from "./bannerdetail-img.svg";
export { default as imageCollage1 } from "./image-grid1.svg";
export { default as imageCollageCore } from "./core-collage.svg";
export { default as eventBg } from "./event.svg";
export { default as savitha } from "./savitha.svg";
export { default as aboutUsImg } from "./aboutus.svg";
export { default as weBelongHero } from "./we-belong-hero.svg";
export { default as coorg } from "./coorg.png";
export { default as logoCenter } from "./center-logo.svg";
export { default as guitarImg } from "./guitar.svg";
export { default as guitarBG } from "./guitar-bg.svg";
export { default as homeCollage1 } from "./Home Collage/home-collage-1.jpg";
export { default as homeCollage2 } from "./Home Collage/home-collage-2.png";
export { default as homeCollage3 } from "./Home Collage/home-collage-3.png";
export { default as homeCollage4 } from "./Home Collage/home-collage-4.png";
export { default as homeCollage5 } from "./Home Collage/home-collage-5.png";
export { default as homeCollage6 } from "./Home Collage/home-collage-6.png";
export { default as homeCollage7 } from "./Home Collage/home-collage-7.png";
export { default as homeCollage8 } from "./Home Collage/home-collage-8.png";
export { default as homeCollage9 } from "./Home Collage/home-collage-9.png";
export { default as community1 } from "./CCC Images/community-1.png";
export { default as community2 } from "./CCC Images/community-2.jpg";
export { default as community3 } from "./CCC Images/community-3.png";
export { default as culture1 } from "./CCC Images/culture-1.png";
export { default as culture2 } from "./CCC Images/culture-2.png";
export { default as culture3 } from "./CCC Images/culture-3.png";
export { default as celebration1 } from "./CCC Images/celebration-1.png";
export { default as celebration2 } from "./CCC Images/celebration-2.png";
export { default as celebration3 } from "./CCC Images/celebration-3.png";
export { default as workshop1 } from "./workshop1.png";
export { default as workshop2 } from "./workshop2.png";
